// Generated by agent: 2025-10-07
namespace Agents.Runtime.Story
{
    public enum StoryNodeType
    {
        Dialogue = 0,
        Investigation = 1,
        Trial = 2,
        Cinematic = 3
    }
}
