// Generated by agent: 2025-10-07
using System;
using System.Collections.Generic;
using UnityEngine;

namespace Agents.Runtime.Story
{
    [Serializable]
    public sealed class StoryNodeDefinition
    {
        [SerializeField]
        private string _nodeId = Guid.NewGuid().ToString("N");

        [SerializeField]
        private string _title = "New Node";

        [SerializeField]
        private StoryNodeType _nodeType = StoryNodeType.Dialogue;

        [SerializeField]
        private List<StoryLineDefinition> _lines = new List<StoryLineDefinition>(4);

        [SerializeField]
        private List<StoryTransition> _transitions = new List<StoryTransition>(2);

        public string NodeId => _nodeId;

        public string Title => _title;

        public StoryNodeType NodeType => _nodeType;

        public IReadOnlyList<StoryLineDefinition> Lines => _lines;

        public IReadOnlyList<StoryTransition> Transitions => _transitions;
    }
}
