// Generated by agent: 2025-10-07
using System;
using Agents.Runtime.Domain;
using UnityEngine;
using UnityEngine.Playables;

namespace Agents.Runtime.Story
{
    [Serializable]
    public sealed class StoryLineDefinition
    {
        [SerializeField]
        private string _speakerId = string.Empty;

        [SerializeField]
        private string _text = string.Empty;

        [SerializeField]
        private AudioClip _voiceClip;

        [SerializeField]
        private PlayableAsset _timeline;

        [SerializeField]
        private ReactionType _reactionType = ReactionType.None;

        public string SpeakerId => _speakerId;

        public string Text => _text;

        public AudioClip VoiceClip => _voiceClip;

        public PlayableAsset Timeline => _timeline;

        public ReactionType Reaction => _reactionType;
    }
}
