// Generated by agent: 2025-10-07
using System.Collections.Generic;
using UnityEngine;

namespace Agents.Runtime.Story
{
    [CreateAssetMenu(fileName = "StoryGraph", menuName = "Agents/Story Graph")]
    public sealed class StoryGraph : ScriptableObject
    {
        [SerializeField]
        private List<StoryNodeDefinition> _nodes = new List<StoryNodeDefinition>(16);

        public IReadOnlyList<StoryNodeDefinition> Nodes => _nodes;
    }
}
