// Generated by agent: 2025-10-07
using System;
using System.Collections.Generic;
using Agents.Runtime.Domain;
using UnityEngine;

namespace Agents.Runtime.Story
{
    [Serializable]
    public sealed class StoryTransition
    {
        [SerializeField]
        private string _targetNodeId = string.Empty;

        [SerializeField]
        private List<FlagRequirement> _flagRequirements = new List<FlagRequirement>(2);

        [SerializeField]
        private List<EvidenceRequirement> _evidenceRequirements = new List<EvidenceRequirement>(1);

        public string TargetNodeId => _targetNodeId;

        public IReadOnlyList<FlagRequirement> FlagRequirements => _flagRequirements;

        public IReadOnlyList<EvidenceRequirement> EvidenceRequirements => _evidenceRequirements;
    }

    [Serializable]
    public struct FlagRequirement
    {
        public string FlagKey;
        public bool ExpectedValue;
    }

    [Serializable]
    public struct EvidenceRequirement
    {
        public string EvidenceId;
        public ReactionType RequiredReaction;
    }
}
