// Generated by agent: 2025-10-07
using Agents.Editor.Utility;
using Agents.Runtime.Config;
using Agents.Runtime.Evidence;
using Agents.Runtime.Story;
using UnityEditor;
using UnityEngine;

namespace Agents.Editor.Windows
{
    public sealed class AgentsDashboardWindow : EditorWindow
    {
        private AgentsRuntimeConfig _runtimeConfig;
        private StoryGraph _storyGraph;
        private EvidenceLibrary _evidenceLibrary;

        [MenuItem("Agents/Dashboard", priority = 0)]
        public static void Open()
        {
            var window = GetWindow<AgentsDashboardWindow>();
            window.titleContent = new GUIContent("Agents Dashboard");
            window.Show();
        }

        private void OnEnable()
        {
            LoadAssets();
        }

        private void OnGUI()
        {
            EditorGUILayout.Space();
            GUILayout.Label("Agents Tooling Overview", EditorStyles.boldLabel);

            if (_runtimeConfig == null)
            {
                EditorGUILayout.HelpBox("Runtime config not found. Click the button below to generate defaults.", MessageType.Warning);
                if (GUILayout.Button("Generate Default Assets"))
                {
                    GenerateDefaults();
                }

                return;
            }

            DrawAssetField("Runtime Config", _runtimeConfig);
            DrawAssetField("Story Graph", _storyGraph);
            DrawAssetField("Evidence Library", _evidenceLibrary);

            EditorGUILayout.Space();
            GUILayout.Label("Workflows", EditorStyles.boldLabel);

            if (GUILayout.Button("Open Story Graph Editor"))
            {
                StoryGraphEditorWindow.Open(_storyGraph);
            }

            if (GUILayout.Button("Open Evidence Library Editor"))
            {
                EvidenceLibraryWindow.Open(_evidenceLibrary);
            }
        }

        private void DrawAssetField(string label, Object asset)
        {
            using (new EditorGUILayout.HorizontalScope())
            {
                EditorGUILayout.LabelField(label, GUILayout.Width(160f));
                EditorGUILayout.ObjectField(asset, typeof(Object), false);
            }
        }

        private void GenerateDefaults()
        {
            _runtimeConfig = AgentsEditorAssetUtility.EnsureRuntimeConfig();
            _storyGraph = AgentsEditorAssetUtility.EnsureStoryGraph();
            _evidenceLibrary = AgentsEditorAssetUtility.EnsureEvidenceLibrary();
            EditorUtility.DisplayDialog("Agents", "Default assets generated.", "OK");
        }

        private void LoadAssets()
        {
            _runtimeConfig = AgentsEditorAssetUtility.EnsureRuntimeConfig();
            _storyGraph = AgentsEditorAssetUtility.EnsureStoryGraph();
            _evidenceLibrary = AgentsEditorAssetUtility.EnsureEvidenceLibrary();
        }
    }
}
