// Generated by agent: 2025-10-07
using System;
using UnityEngine;

namespace Agents.Runtime.Evidence
{
    [Serializable]
    public sealed class EvidenceItem
    {
        [SerializeField]
        private string _evidenceId = Guid.NewGuid().ToString("N");

        [SerializeField]
        private string _displayName = "New Evidence";

        [SerializeField]
        [TextArea]
        private string _description = string.Empty;

        [SerializeField]
        private Sprite _icon;

        [SerializeField]
        private AudioClip _voiceClip;

        public string EvidenceId => _evidenceId;

        public string DisplayName => _displayName;

        public string Description => _description;

        public Sprite Icon => _icon;

        public AudioClip VoiceClip => _voiceClip;
    }
}
