// Generated by agent: 2025-10-07
using System.Collections.Generic;
using UnityEngine;

namespace Agents.Runtime.Evidence
{
    [CreateAssetMenu(fileName = "EvidenceLibrary", menuName = "Agents/Evidence Library")]
    public sealed class EvidenceLibrary : ScriptableObject
    {
        [SerializeField]
        private List<EvidenceItem> _entries = new List<EvidenceItem>(16);

        public IReadOnlyList<EvidenceItem> Entries => _entries;
    }
}
