// Generated by agent: 2025-10-07
using System;

namespace Agents.Runtime.Core.Eventing
{
    public interface IEventBus
    {
        void Publish<TEvent>(TEvent payload);

        void Subscribe<TEvent>(Action<TEvent> handler);

        void Unsubscribe<TEvent>(Action<TEvent> handler);
    }
}
