// Generated by agent: 2025-10-07
namespace Agents.Editor.Infrastructure
{
    internal static class AgentsAssetPaths
    {
        public const string AgentsRoot = "Assets/Agents";
        public const string SettingsFolder = "Assets/Agents/Settings";
        public const string DataFolder = "Assets/Agents/Data";
        public const string ConfigAssetPath = "Assets/Agents/Settings/AgentsRuntimeConfig.asset";
        public const string EvidenceLibraryPath = "Assets/Agents/Data/EvidenceLibrary.asset";
        public const string StoryGraphPath = "Assets/Agents/Data/StoryGraph.asset";
    }
}
