// Generated by agent: 2025-10-07
using Agents.Runtime.Evidence;
using Agents.Runtime.Story;
using UnityEngine;

namespace Agents.Runtime.Config
{
    [CreateAssetMenu(fileName = "AgentsRuntimeConfig", menuName = "Agents/Runtime Config")]
    public sealed class AgentsRuntimeConfig : ScriptableObject
    {
        [SerializeField]
        private StoryGraph _storyGraph;

        [SerializeField]
        private EvidenceLibrary _evidenceLibrary;

        public StoryGraph StoryGraph => _storyGraph;

        public EvidenceLibrary EvidenceLibrary => _evidenceLibrary;
    }
}
