// Generated by agent: 2025-10-07
using System.Collections.Generic;

namespace Agents.Runtime.Domain
{
    /// <summary>
    /// Keeps track of story flags used for branching logic.
    /// </summary>
    public sealed class FlagState
    {
        private readonly Dictionary<string, bool> _flags = new Dictionary<string, bool>(32);

        public bool GetFlag(string key)
        {
            if (string.IsNullOrEmpty(key))
            {
                return false;
            }

            if (_flags.TryGetValue(key, out var value))
            {
                return value;
            }

            return false;
        }

        public void SetFlag(string key, bool value)
        {
            if (string.IsNullOrEmpty(key))
            {
                return;
            }

            _flags[key] = value;
        }
    }
}
