// Generated by agent: 2025-10-07
namespace Agents.Runtime.Domain
{
    public enum ReactionType
    {
        None = 0,
        Objection = 1,
        Contradiction = 2,
        Support = 3,
        Pursuit = 4,
        PresentEvidence = 5
    }
}
