// Generated by agent: 2025-10-07
namespace Agents.Runtime.Core.Services
{
    public interface IServiceLocator
    {
        void Register<TService>(TService instance);

        TService Resolve<TService>();

        bool TryResolve<TService>(out TService service);
    }
}
